check if /var/log is already tmpfs

diff --git a/deb/usr/lib/ramlog-oe/ramlog-oe b/deb/usr/lib/ramlog-oe/ramlog-oe
--- a/deb/usr/lib/ramlog-oe/ramlog-oe
+++ b/deb/usr/lib/ramlog-oe/ramlog-oe
@@ -20,15 +20,18 @@ LOG2RAM_LOG="ramlog-oe.log"
 LOG_OUTPUT="tee -a ${HDD_LOG}/$LOG2RAM_LOG"
 
 isSafe() {
-    if [ ! -d $HDD_LOG ]; then
-        echo "ERROR: $HDD_LOG doesn't exist! Can't sync." >&2
+    if findmnt ${RAM_LOG} >/dev/null 2>&1; then
+        echo "ERROR: ${RAM_LOG} is already mounted." >&2
         exit 1
     fi
-    NoCache=$(which nocache 2>/dev/null)
+    if findmnt ${HDD_LOG} >/dev/null 2>&1; then
+        echo "ERROR: ${HDD_LOG} is already mounted." >&2
+        exit 2
+    fi
 }
 
 syncToDisk() {
-    echo -e "\n\n$(date): Syncing logs to storage\n" | $LOG_OUTPUT
+    echo -e "\n\n$(date): Syncing logs to storage\n" | ${LOG_OUTPUT}
     syncLogDir ${RAM_LOG} ${HDD_LOG}
 }
 
@@ -39,7 +42,16 @@ syncFromDisk() {
 
 # $1 -> source directory, $2 -> target directory
 syncLogDir() {
-    isSafe
+    if [ ! -d ${HDD_LOG} ]; then
+        echo "ERROR: ${HDD_LOG} doesn't exist! Can't sync." >&2
+        exit 3
+    fi
+    if [ ! -d ${RAM_LOG} ]; then
+        echo "ERROR: ${RAM_LOG} doesn't exist! Can't sync." >&2
+        exit 4
+    fi
+    NoCache=$(which nocache 2>/dev/null)
+
     if [ "$USE_RSYNC" = true ]; then
         ${NoCache} rsync --archive --xattrs --whole-file --verbose --delete --exclude "lost+found" --exclude "${LOG2RAM_LOG}" --links "${1}/" "${2}" 2>&1 | ${LOG_OUTPUT}
     else
@@ -50,9 +62,11 @@ syncLogDir() {
 
 case "$1" in
 start)
-    mkdir -p $HDD_LOG
-    mount --bind $RAM_LOG $HDD_LOG
-    mount --make-private $HDD_LOG
+    isSafe
+
+    mkdir -p ${HDD_LOG}
+    mount --bind ${RAM_LOG} ${HDD_LOG}
+    mount --make-private ${HDD_LOG}
 
     # Check whether zram device is available or we need to use tmpfs
     LOG_TYPE="tmpfs"
@@ -64,12 +78,12 @@ start)
     done
     case $LOG_TYPE in
     zram)
-        echo -e "Mounting $rd as $RAM_LOG \c" | $LOG_OUTPUT
-        mount --options discard $rd $RAM_LOG 2>&1 | $LOG_OUTPUT
+        echo -e "Mounting $rd as ${RAM_LOG} \c" | ${LOG_OUTPUT}
+        mount --options discard $rd ${RAM_LOG} 2>&1 | ${LOG_OUTPUT}
         ;;
     tmpfs)
-        echo -e "Setting up $RAM_LOG as tmpfs \c" | $LOG_OUTPUT
-        mount --types tmpfs --options nosuid,noexec,nodev,mode=0755,size=$SIZE ramlog-oe $RAM_LOG 2>&1 | $LOG_OUTPUT
+        echo -e "Setting up ${RAM_LOG} as tmpfs \c" | ${LOG_OUTPUT}
+        mount --types tmpfs --options nosuid,noexec,nodev,mode=0755,size=$SIZE ramlog-oe ${RAM_LOG} 2>&1 | ${LOG_OUTPUT}
         ;;
     esac
 
@@ -77,15 +91,15 @@ start)
     ;;
 stop)
     syncToDisk
-    umount --lazy $RAM_LOG
-    umount --lazy $HDD_LOG
-    rmdir $HDD_LOG
+    umount --lazy ${RAM_LOG}
+    umount --lazy ${HDD_LOG}
+    rmdir ${HDD_LOG}
     ;;
 write)
     syncToDisk
     ;;
 *)
     echo "Usage: ${0##*/} {start|stop|write}" >&2
-    exit 1
+    exit 5
     ;;
 esac
